spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project-tracking?createDatabaseIfNotExist=true
    username: root
    password: 123456
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
